/*
 * REST API сервиса интеграции кассетниц ТЛД
 *
 * Интерфейс Прикладного Программирования выдачи ТЛД
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Описание данных ошибки запросов
type Fault struct {
	// Идентификатор ошибки
	Id string `json:"id,omitempty"`
	// Описание ошибки
	Description string `json:"description,omitempty"`
}
