/*
 * REST API сервиса интеграции кассетниц ТЛД
 *
 * Интерфейс Прикладного Программирования выдачи ТЛД
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"BELAESPDS001IF0001",
		strings.ToUpper("Get"),
		"/tld/take",
		BELAESPDS001IF0001,
	},

	Route{
		"BELAESPDS001IF0002",
		strings.ToUpper("Post"),
		"/tld/take",
		BELAESPDS001IF0002,
	},

	Route{
		"BELAESPDS001IF0009",
		strings.ToUpper("Get"),
		"/tld/drop",
		BELAESPDS001IF0009,
	},

	Route{
		"BELAESPDS001IF0010",
		strings.ToUpper("Get"),
		"/tld/drop/cells",
		BELAESPDS001IF0010,
	},

	Route{
		"BELAESPDS001IF0011",
		strings.ToUpper("Post"),
		"/tld/contamination",
		BELAESPDS001IF0011,
	},

	Route{
		"BELAESPDS001IF0012",
		strings.ToUpper("Post"),
		"/tld/drop",
		BELAESPDS001IF0012,
	},
}
